# -*- coding: utf-8 -*-
"""GRIDPreprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DIArVk9iWP-ZjSvikeposlvEEs5Uld-w

# DATA PREPARE
"""

from numpy import zeros
import pandas as pd
import numpy as np

# Base Directory
DIR = './'

DATASET_TRAIN = DIR + 'GeoLifeBeijing_sample.csv'
SAVE_TRAIN = DIR_GRID + 'GeoLifeBeijing_grid_sample.csv'

# Load dataset
df_train = pd.read_csv(DATASET_TRAIN)
lats_train = df_train['lat'].values
lons_train = df_train['lon'].values
min_lats = min(lats_train)
max_lats = max(lats_train)
min_lons = min(lons_train)
max_lons = max(lons_train)

min_lats = np.round(min_lats-0.005, 2)
max_lats = np.round(max_lats+0.005, 2)
min_lons = np.round(min_lons-0.005, 2)
max_lons = np.round(max_lons+0.005, 2)

gridx_total = int(np.round((max_lons - min_lons)/0.01))
gridy_total = int(np.round((max_lats - min_lats)/0.01))

df_train['lon'] = ((df_train['lon'] - min_lons)*100).astype('int64') + 1
df_train['lat'] = ((df_train['lat'] - min_lats)*100).astype('int64') + 1

df_train.to_csv(SAVE_TRAIN, header = True, index = False)
