# -*- coding: utf-8 -*-
"""GRIDPreprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DIArVk9iWP-ZjSvikeposlvEEs5Uld-w

# DATA PREPARE
"""

from numpy import zeros
import pandas as pd
import numpy as np

# Base Directory
DIR = './data/'
DIR_GRID = './griddata/'

DATASET_TRAIN = DIR + 'GeoLifeBeijing_train.csv'
DATASET_TEST = DIR + 'GeoLifeBeijing_test.csv'
SAVE_TRAIN = DIR_GRID + 'GeoLifeBeijing_grid_train.csv'
SAVE_TEST = DIR_GRID + 'GeoLifeBeijing_grid_test.csv'

# Load dataset
df_train = pd.read_csv(DATASET_TRAIN)
df_test = pd.read_csv(DATASET_TEST)

lats_train = df_train['lat'].values
lons_train = df_train['lon'].values
lats_test = df_test['lat'].values
lons_test = df_test['lon'].values

min_lats = min(min(lats_train), min(lats_test))
max_lats = max(max(lats_train), max(lats_test))
min_lons = min(min(lons_train), min(lons_test))
max_lons = max(max(lons_train), max(lons_test))

min_lats = np.round(min_lats-0.005, 2)
max_lats = np.round(max_lats+0.005, 2)
min_lons = np.round(min_lons-0.005, 2)
max_lons = np.round(max_lons+0.005, 2)

gridx_total = int(np.round((max_lons - min_lons)/0.01))
gridy_total = int(np.round((max_lats - min_lats)/0.01))

df_train['lon'] = ((df_train['lon'] - min_lons)*100).astype('int64') + 1
df_train['lat'] = ((df_train['lat'] - min_lats)*100).astype('int64') + 1
df_test['lon'] = ((df_test['lon'] - min_lons)*100).astype('int64') + 1
df_test['lat'] = ((df_test['lat'] - min_lats)*100).astype('int64') + 1

df_train.to_csv(SAVE_TRAIN, header = True, index = False)
df_test.to_csv(SAVE_TEST, header = True, index = False)